#!/bin/sh

if [ ! -e protocol/stamp ] ; then
	# The Makefile fragments generated by the protocol library must be
	# valid before Automake runs, or it will choke.  We could just
	# create empty fragments with old timestamps to force them to be
	# updated when "make" is run; but in this case, Automake does a full
	# am-refresh for some reason and fails to update the depfiles, so the
	# build fails.  However, if the fragments are valid initially, then on
	# any subsequent update of protocol.asn, Automake will properly rebuild
	# the depfiles and the right thing will happen.  Odd.
	asnfiles=`grep ^ASNFILES protocol/Makefile.am | cut -f2 -d=`
	(cd protocol && ./compile.pl $asnfiles) || exit 1
fi

if [ -e configure ] ; then
	# If we've run before, do a fast refresh unless we're told otherwise.
	if [ "$1" = "-f" -o "$1" = "--force" ] ; then
		autoreconf --install --force
	else
		autoreconf
	fi
else
	autoreconf --install --force
fi
