#!/bin/sh

cond_move() {
	src=$1
	dest=$2
	if [ -f $dest ] && cmp -s $src $dest ; then
		# No need to rebuild if the actual content of $dest
		# hasn't changed
		rm -f $src
	else
		mv $src $dest
	fi
}

# XXX check for asn1c
# XXX add "file is autogenerated" warnings to protocol.mk and support/* classes/*

tempfile="output.$$"
classrules="classes/classes.$$"
supportrules="support/support.$$"
trap "rm -f $tempfile $classrules $supportrules" EXIT

asn1c -Werror -fskeletons-copy $* > $tempfile 2>&1
result=$?
egrep -v "^(Copied|Generated|Compiled)" $tempfile >&2
if [ $result != 0 ] ; then
	exit $result
fi

set -e

rm -f Makefile.am.sample converter-sample.c
generated=`awk '/^Compiled/ {print $2}' $tempfile`
copied=`awk '/^Copied/ {print $NF}' $tempfile`

echo "CLASS_FILES = " > $classrules
for file in $generated
do
	cond_move $file classes/$file
	echo "CLASS_FILES += $file" >> $classrules
done
cond_move $classrules classes/classes.mk

echo "SUPPORT_FILES = " > $supportrules
for file in $copied
do
	# Filter out converter-sample.c
	[ -f $file ] || continue
	cond_move $file support/$file
	echo "SUPPORT_FILES += $file" >> $supportrules
done
cond_move $supportrules support/support.mk

touch stamp
