#!/bin/sh

cond_move() {
	src=$1
	dest=$2
	if [ -f $dest ] && cmp -s $src $dest ; then
		# No need to rebuild if the actual content of $dest
		# hasn't changed
		rm -f $src
	else
		mv $src $dest
	fi
}

# XXX check for asn1c
# XXX add "file is autogenerated" warnings to protocol.mk and support/* classes/*

tempfile="output.$$"
makerules="protocol.$$"
trap "rm -f $tempfile $makerules" EXIT

asn1c -Werror -fskeletons-copy $* > $tempfile 2>&1
result=$?
egrep -v "^(Copied|Generated|Compiled)" $tempfile >&2
if [ $result != 0 ] ; then
	exit $result
fi

set -e

rm -f Makefile.am.sample converter-sample.c
generated=`awk '/^Compiled/ {print $2}' $tempfile`
copied=`awk '/^Copied/ {print $NF}' $tempfile`

mkdir -p classes
echo "CLASS_FILES = " > $makerules
for file in $generated
do
	cond_move $file classes/$file
	echo "CLASS_FILES += classes/$file" >> $makerules
done

mkdir -p support
echo -e "\nSUPPORT_FILES = " >> $makerules
for file in $copied
do
	# Filter out converter-sample.c
	[ -f $file ] || continue
	cond_move $file support/$file
	echo "SUPPORT_FILES += support/$file" >> $makerules
done
cond_move $makerules protocol.mk
