/* AUTOGENERATED FILE -- DO NOT EDIT */

/**
 * @file
 * @brief Server stubs for the example protocol
 * @addtogroup example
 * @{
 * @defgroup server Server Stubs
 * @{
 */

#ifndef EXAMPLE_SERVER_H
#define EXAMPLE_SERVER_H

#include "example_minirpc.h"

extern struct mrpc_protocol example_server;

struct example_server_operations {
	mrpc_status_t (*ChooseColor)(void *conn_data, struct mrpc_message *msg,
			ColorChoice *in);
	mrpc_status_t (*GetNumColors)(void *conn_data, struct mrpc_message *msg,
			Count *out);
	void (*CrayonSelected)(void *conn_data, struct mrpc_message *msg,
			Color *in);
};

int example_server_set_operations(struct mrpc_connection *conn,
			const struct example_server_operations *ops);

mrpc_status_t example_ChooseColor_send_async_reply(struct mrpc_message *request);
mrpc_status_t example_GetNumColors_send_async_reply(struct mrpc_message *request,
			Count *out);

mrpc_status_t example_ChooseColor_send_async_reply_error(struct mrpc_message *request,
			mrpc_status_t status);
mrpc_status_t example_GetNumColors_send_async_reply_error(struct mrpc_message *request,
			mrpc_status_t status);

/**
 * @}
 * @}
 */

#endif
