/* AUTOGENERATED FILE -- DO NOT EDIT */

/**
 * @file
 * @brief Data structures for the example protocol
 * @addtogroup example_common
 * @{
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef EXAMPLE_XDR_H
#define EXAMPLE_XDR_H

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Generated enum corresponding to example_color XDR type
 */
enum example_color {
	RED = 0,
	ORANGE = 1,
	YELLOW = 2,
	GREEN = 3,
	BLUE = 4,
	INDIGO = 5,
	VIOLET = 6,
};
/**
 * @brief Generated typedef for example_color XDR type
 */
typedef enum example_color example_color;

/**
 * @brief Generated struct corresponding to example_color_choice XDR type
 */
struct example_color_choice {
	/**
	 * @brief The @c acceptable variable-length array
	 */
	struct {
		u_int acceptable_len;
		enum Color *acceptable_val;
	} acceptable;
	/**
	 * @brief The @c preferred enum
	 */
	enum example_color preferred;
};
/**
 * @brief Generated typedef for example_color_choice XDR type
 */
typedef struct example_color_choice example_color_choice;

/**
 * @brief Generated typedef corresponding to example_count XDR typedef
 */
typedef int example_count;


/* The xdr functions.  The application should never need to call these
   directly. */
/**
 * @cond SHOW_XDR_PROCS
 */
#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_example_color (XDR *, Color*);
extern  bool_t xdr_example_color_choice (XDR *, ColorChoice*);
extern  bool_t xdr_example_count (XDR *, Count*);

#else /* K&R C */
extern bool_t xdr_example_color ();
extern bool_t xdr_example_color_choice ();
extern bool_t xdr_example_count ();

#endif /* K&R C */
/**
 * @endcond
 */

#ifdef __cplusplus
}
#endif

#endif /* !EXAMPLE_XDR_H */

/**
 * @}
 */
